name: backgammon
version: 0.0.1
description: Backgammon Client
dependencies:
  browser: any
  yaml: any
  play_phaser: any
  play_pixi: any
  dartemis: any
  dilithium: any

dev_dependencies:
#  unittest: any
transformers:
- $dart2js:
    checked: false
    minify: true
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true
    csp: true
